### ISSUE TITLE
check password hash throwing error on incorrect password

### ISSUE THREAD

**Issue by adnanshussain** [adnanshussain/FintechPy#1]
if user.password != self.password.data and not check_password_hash(user.password, self.password.data):
            raise validators.ValidationError('Invalid password')

The above line throws an error with a hard coded value of ftAdmin123 if an incorrect password is given.

**Comment by mohammadparyal** [comment]
Hi Adnan, 

Its working on my side, I have checked with normal password and hashed password its working in both cases, tried above mentioned password its working also.

![image](https://cloud.githubusercontent.com/assets/1651928/17201771/9cf318c8-54a2-11e6-90ff-6c2b5cf6127d.png)

These above passwords i tried and checked invalid case also 
Need more details about this issue 
One more issue i found on new login form its not showing validation messages which i will fix asap

Thanks

**Comment by adnanshussain** [comment]
Was a mistake issue.
