### ISSUE TITLE
Create Event form not showing newly added Event Group

### ISSUE THREAD

**Issue by adnanshussain** [adnanshussain/FintechPy#3]
@harisahmed11 

When I add a new event group and then try to add an event, it does not show the newly added event group in the Dropdown.

If I restart the application the newly added event group starts to show. I think its a flask admin caching issue. 

Please check and solve it.

**Comment by adnanshussain** [comment]
?

**Comment by harisahmed11** [comment]
This issue is resolved, Now it's working fine.
