### ISSUE TITLE
Point #6 Still not working. When I try to type in a date manually. It's not functioning properly

### ISSUE THREAD

**Issue by adnanshussain** [adnanshussain/FintechPy#6]
@juzar4u  @harisahmed11 

Why was this not fixed in the last pull request ?

**Comment by adnanshussain** [comment]
This is still not working properly. Am I missing something or you don't test your code after writing it ?

**Comment by harisahmed11** [comment]
I have reviewed the issue, by cloning your main branch and I found over code are not properly updated there, their's still the code which we commit in first pull request. This issues are occur after merging the Second pull request so, Now we're working to find out why this happend
